name: totalslider
repo: git://github.com/username/projectname.git
deploy_user: deploy
user: totalslider
access_users:
  - deploy
  - totalslider
  - peter
  - chris
group: totalslider-group
theme: themename
domain: total-slider-test.com

alerts:
  hipchat:
    room:
    key:

stage:
  dev:
    ip: 127.0.0.1
    http_port: 15080
    ssh_port: 22080
    user: vagrant
    upload_url_path: 
    upload_path: 
  staging:
    ip: 0.0.0.0
    ssh_port: 0
    user: deploy
    upload_url_path: 
    upload_path: 
  production:
    ip: 0.0.0.0
    ssh_port: 0
    user: deploy
    upload_url_path: 
    upload_path: 
